# 允许的最大行宽
line-length = 120

[lint]
# 选择要开启的规则
# E = 错误, F = Pyflakes (基础错误), I = 自动排序 import
select = ["E", "F", "I"]

# 忽略那些烦人的规则
ignore = [
    "E501", # 行太长（我们已经设了120，超一点点别报错）
    "F401", # 允许导入了但没使用的变量（写代码调试时很有用）
]

[format]
# 格式化时使用单引号还是双引号
quote-style = "double"
